version: 2
updates:
  - package-ecosystem: pip
    directory: /CyberArmyV10.7.15
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
