"""Generate observation-only Frida scripts for self-hosted lab binaries."""

import json
import re
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict

from .local_lab_policy import LocalLabError, LocalLabPolicy


class ObservationScriptBuilder:
    """Create a symbol trace that logs calls but never patches memory or returns."""

    SYMBOL_PATTERN = re.compile(r'^[A-Za-z_?$@][A-Za-z0-9_?$@:.<>~-]{0,199}$')

    def __init__(self, config: Dict[str, Any]):
        self.policy = LocalLabPolicy(config)
        output_dir = self.policy.config.get('trace_output_dir', 'state/lab_traces')
        self.output_dir = self.policy.require_workspace_file(output_dir, must_exist=False)

    def build(self, symbol: str) -> str:
        self.policy.require_valid()
        if not self.SYMBOL_PATTERN.fullmatch(symbol):
            raise LocalLabError('Symbol contains unsupported characters')

        encoded_symbol = json.dumps(symbol)
        authorization = json.dumps(self.policy.authorization_reference)
        script = f'''// Observation-only trace generated by CyberArmy.
// No return-value replacement, memory writes, offsets, or export patching.
const authorizationReference = {authorization};
const symbolName = {encoded_symbol};
const target = Module.findExportByName(null, symbolName);
if (target === null) {{
  throw new Error("Symbol not found: " + symbolName);
}}
Interceptor.attach(target, {{
  onEnter(args) {{
    console.log(JSON.stringify({{
      event: "enter",
      symbol: symbolName,
      authorizationReference: authorizationReference,
      threadId: Process.getCurrentThreadId()
    }}));
  }},
  onLeave(retval) {{
    console.log(JSON.stringify({{
      event: "leave",
      symbol: symbolName,
      authorizationReference: authorizationReference,
      returnValue: retval.toString()
    }}));
  }}
}});
'''

        self.output_dir.mkdir(parents=True, exist_ok=True)
        safe_name = re.sub(r'[^A-Za-z0-9_-]+', '_', symbol).strip('_')[:60] or 'symbol'
        timestamp = datetime.now(timezone.utc).strftime('%Y%m%d_%H%M%S')
        output_path = self.output_dir / f'trace_{safe_name}_{timestamp}.js'
        output_path.write_text(script, encoding='utf-8')
        return str(output_path)
